package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/99designs/gqlgen/graphql"

	"graphql-gateway/internal/dataloaders"
	"graphql-gateway/internal/generated"
	"graphql-gateway/internal/models"
)

// Post is the resolver for the post field.
func (r *commentResolver) Post(ctx context.Context, obj *models.Comment) (*models.Post, error) {
	post, err := dataloaders.For(ctx).PostByID.Load(ctx, obj.PostID)
	if err != nil {
		r.Log.Error("resolve comment.post failed", "commentId", obj.ID, "postId", obj.PostID, "error", err)
		return nil, err
	}
	return post, nil
}

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *models.Comment) (*models.User, error) {
	author, err := dataloaders.For(ctx).UserByID.Load(ctx, obj.AuthorID)
	if err != nil {
		r.Log.Error("resolve comment.author failed", "commentId", obj.ID, "authorId", obj.AuthorID, "error", err)
		return nil, err
	}
	return author, nil
}

// User is the resolver for the user field.
func (r *postResolver) User(ctx context.Context, obj *models.Post) (*models.User, error) {
	user, err := dataloaders.For(ctx).UserByID.Load(ctx, obj.UserID)
	if err != nil {
		r.Log.Error("resolve post.user failed", "postId", obj.ID, "userId", obj.UserID, "error", err)
		return nil, err
	}
	return user, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *models.Post) ([]*models.Comment, error) {
	comments, err := dataloaders.For(ctx).CommentsByPost.Load(ctx, obj.ID)
	if err != nil {
		r.Log.Error("resolve post.comments failed", "postId", obj.ID, "error", err)
		return nil, err
	}
	if comments == nil {
		comments = []*models.Comment{}
	}
	return comments, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	user, err := dataloaders.For(ctx).UserByID.Load(ctx, id)
	if err != nil {
		r.Log.Error("resolve query.user failed", "id", id, "error", err)
		return nil, err
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, ids []string) ([]*models.User, error) {
	values, errs := dataloaders.For(ctx).UserByID.LoadAll(ctx, ids)

	out := make([]*models.User, 0, len(values))
	for i, v := range values {
		if err := errs[i]; err != nil {
			r.Log.Error("resolve query.users item failed", "id", ids[i], "error", err)
			graphql.AddErrorf(ctx, "user %s: %v", ids[i], err)
			continue
		}
		out = append(out, v)
	}
	return out, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*models.Post, error) {
	post, err := dataloaders.For(ctx).PostByID.Load(ctx, id)
	if err != nil {
		r.Log.Error("resolve query.post failed", "id", id, "error", err)
		return nil, err
	}
	return post, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, userID string) ([]*models.Post, error) {
	posts, err := dataloaders.For(ctx).PostsByUserID.Load(ctx, userID)
	if err != nil {
		r.Log.Error("resolve query.posts failed", "userId", userID, "error", err)
		return nil, err
	}
	if posts == nil {
		posts = []*models.Post{}
	}
	return posts, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*models.Comment, error) {
	comment, err := dataloaders.For(ctx).CommentByID.Load(ctx, id)
	if err != nil {
		r.Log.Error("resolve query.comment failed", "id", id, "error", err)
		return nil, err
	}
	return comment, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string) ([]*models.Comment, error) {
	comments, err := dataloaders.For(ctx).CommentsByPost.Load(ctx, postID)
	if err != nil {
		r.Log.Error("resolve query.comments failed", "postId", postID, "error", err)
		return nil, err
	}
	if comments == nil {
		comments = []*models.Comment{}
	}
	return comments, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *models.User) ([]*models.Post, error) {
	posts, err := dataloaders.For(ctx).PostsByUserID.Load(ctx, obj.ID)
	if err != nil {
		r.Log.Error("resolve user.posts failed", "userId", obj.ID, "error", err)
		return nil, err
	}
	if posts == nil {
		posts = []*models.Post{}
	}
	return posts, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	commentResolver struct{ *Resolver }
	postResolver    struct{ *Resolver }
	queryResolver   struct{ *Resolver }
	userResolver    struct{ *Resolver }
)
